package com.example.admin.User;

import com.example.admin.common.api.CommonResult;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

@RestController
@RequestMapping("/api/user")
public class UserController {
  private static final Logger LOGGER = LoggerFactory.getLogger(UserController.class);

  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping()
  public @ResponseBody CommonResult<User> addNewUser (@RequestBody @Valid User user, BindingResult bindingResult) {
    if (bindingResult.hasErrors()) {
      return CommonResult.validateFailed();
    }

    User n = new User();
    n.setName(user.getName());
    n.setEmail(user.getEmail());
    User nUser = userRepository.save(n);

    return CommonResult.success(nUser);
  }

  @GetMapping()
  public @ResponseBody CommonResult<List<User>> getAllUsers() {
    List<User> users = (List<User>) userRepository.findAll();

    LOGGER.info("获取用户列表数据成功");
    return CommonResult.success(users);
  }
}